
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ser
  namespace: dev
  labels:
    app: redis-dep
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

