FROM httpd:latest
COPY index.html /usr/local/apache2/htdocs/index.html 
ENV Name webserver
# ADD . /code -- copy all files to folder called "code"
#ADD index.html /code -- copy index.html to file called "code"
#ADD index.html /code/index.html -- copu index.html inside the folder "code".
